# global default
container:
  image: gcc:latest
  
test_task:
  env:
    matrix:
      STDFLAG:-std=c++14
      STDFLAG:-std=c++17
  test_script: cd test && make -j4 showcxxversion default && make test
  
use_gtest_task:
  env:
    USE_GTEST:1
  container:
    image: srzzumix/googletest:latest
  test_script: cd test && make -j4 showcxxversion default && make test
  
