build:
    environment:
        python: 3.6.0
#    dependencies:
#        before:
#            - pip install tox
    tests:
        before:
            - make -C tools/fused
        override:
            - tox
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - py-scrutinizer-run

filter:
    excluded_paths:
        - '*/test/*'

checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true
