version: 1.0.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      PROJECT_DIR: msvc12
      CMAKE_GENERATOR_NAME: Visual Studio 12 2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PROJECT_DIR: msvc14
      CMAKE_GENERATOR_NAME: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PROJECT_DIR: msvc15
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017
    - BUILD_NUGET: yes

configuration:
  - Debug
  - Release

matrix:
  exclude:
    - configuration: Debug
      BUILD_NUGET: yes
      
clone_depth: 1

before_build:
  - cmd: >-
      mkdir build && cd build

      cmake ../projects/cmake -G "%CMAKE_GENERATOR_NAME%" -Dbuild_gtest_samples=ON

      cd ..

build:
  project: build\iutest.sln
  parallel: true
  verbosity: minimal

test_script:
  - cmd: >-
      cd build

      ctest -C %Configuration% -V

for:
-
  matrix:
    only:
      - configuration: Release
        BUILD_NUGET: yes

  build_script:
    ps: |
      $nuspecPath = "projects\nuget\iutest.nuspec"
      Write-Output "Building NuGet package"
      nuget pack $nuspecPath -OutputDirectory ".\"

notifications:
  - provider: Email
    to:
      - zumix.cpp@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
