
jobs:
  - template: .ci/azure_pipelines/template-make-test.yml
    parameters:
      name: default
  - template: .ci/azure_pipelines/template-make-disabled-test.yml
    strategy:
      matrix:
        AnyParamTest:
          DISABLED_CONFIG: IUTEST_HAS_ANY_PARAM_TEST
