trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - azure-pipelines/*
    exclude:
      - feature/*
      - test/*
  paths:
    include:
      - azure-pipelines.yml
      - .ci/azure_pipelins/*
    exclude:
      - "*.md"
      - "*.yml"
      - docs/*

jobs:
  - job: syntax_test
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: make -C test -j4 syntax_tests_run
        displayName: 'syntax test'
  - template: .ci/azure_pipelines/template-make-test.yml
    parameters:
      name: default
  - template: .ci/azure_pipelines/template-make-disabled-test.yml
    parameters:
      name: disabled
  - template: .ci/azure_pipelines/template-make-nofeature-test.yml
    parameters:
      name: nofeature
