# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# disable config jobs template
parameters:
  name: ''
  options: ''
  vmImage: 'ubuntu 16.04'

jobs:
  - job: ${{ parameters.name }}
    strategy:
      matrix:
        AnyParamTest:
          DISABLED_CONFIG: IUTEST_HAS_ANY_PARAM_TEST
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - script: make -C test -j4 OUTPUTXML=junit ${{ parameters.options }} DEFS+=-D${DISABLED_CONFIG}=0
      displayName: 'make'
    - script: make -C test -j4 OUTPUTXML=junit ${{ parameters.options }} DEFS+=-D${DISABLED_CONFIG}=0 test
      displayName: 'test'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'test/*.xml'

