# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# template steps

parameters:
  name: ''
  vmImage: 'ubuntu 16.04'

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - script: make -C test -j4 OUTPUTXML=junit
      displayName: 'make'
    - script: make -C test -j4 OUTPUTXML=junit test
      displayName: 'test'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'test/*.xml'
